### ISSUE TITLE
After OTP transaction i got  error

### ISSUE THREAD

**Issue by smilydronavalli** [Judopay/JudoKitObjC#81]
Hi,
I am using /transactions/payments API for payment after I got output {"receiptId":"258210036584087552",
"result":"Requires 3D Secure","message":"Issuer authentication required",
"acsUrl":"https://secure.axisbank.com/acs-web-axis/EnrollWeb/AxisBank/server/AccessControlServer?idct=8111.V&vmid=VEReq5426563249",
"md":"171213123430275001050864",
"paReq":"eJxVUstu2zAQvBfoPwg6Fo4pkrIlCmsGTow4LpJUcNMWzU0mN7YAPRxKjp2/LylLScPTzr64O7NweSoL7xVNk9fVzKfjwPewUrXOq+3M//V4cxH7l/LrF3jcGcTFT1QHgxLusWmyLXq5nvnpfI0vgk6iYMJjFvkSOo+Evqu0TccMyABtsVG7rGolZOrlavUgQ0GnUQSkh1CiWS2kbcmE4Dw4PyBnN1RZibLJimyD+mJ5lXqfHpAuDqo+VK15kzGbAhkAHEwhd227Twg5Ho9jN8YWSxyrugTigkA+pksPzmpss1OupS5/7ze3N6enpXjdLNf06U9rNN81WP2dAXEZoLMWJQtoRBnlHmUJDxNuB+/8kJVuCseGdfUA9u6PeR9xgf8dYMk2Vo1hiwEBnvZ1hTbD0vpug8ZGybnqll2jWumETigXIhh513V19jAn0TQeeff1Ji9wjc+JZThmtuyuVu9Vk5iKkff9oGuHg4DHYRjZKv1m2c3Vwv5kknl69430QnQ62E3dCEA+mLu+dSqr1go3EEPjIORU2I7bB1akQv9wyncpbrHc6sRoEHabOQDENSH9UZH+9Kz16ST/AbE14I0="
} 
I will display this content in JP3DSWebView.After I will enter OTP when I click on submit.But I checked in judo pay site payment is displayed as failed.please kindly help me how can I do that.

**Comment by linkthrow** [comment]
hey @smilydronavalli , did you get this resolved as we are encountering this also?

**Comment by aadilsheth** [comment]
Hi @smilydronavalli and @linkthrow 

Could you please contact us on developersupport@judopayments.com so we could arrange a telephone call/remote session to look into the problem at hand.

We need to understand your implementation in order to conclude a thorough investigation. Please contact us providing your Judo ID.

Thank you,

Aadil Sheth
Developer Support
